'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import {
  FileText,
  Download,
  Plus,
  FileSpreadsheet,
  FileJson,
  FileCode,
  Shield,
  TrendingUp,
  Calendar,
  User,
  PenTool,
  Loader2,
  CheckCircle2,
} from 'lucide-react';
import { PageContainer, SectionTitle, SeverityBadge } from '@/components/shared';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { useReports, useDashboardStats } from '@/hooks/use-data';
import { supabase } from '@/lib/supabase';
import { toast } from 'sonner';
import { formatDistanceToNow } from 'date-fns';

const reportTypes = [
  { id: 'incident', label: 'Incident Report', icon: Shield, description: 'Detailed incident analysis with timeline' },
  { id: 'investigation', label: 'Investigation Report', icon: FileText, description: 'OSINT investigation findings' },
  { id: 'threat_summary', label: 'Threat Summary', icon: TrendingUp, description: 'Executive threat landscape summary' },
  { id: 'executive', label: 'Executive Report', icon: FileText, description: 'High-level summary for leadership' },
  { id: 'soc', label: 'SOC Report', icon: Shield, description: 'Security operations center metrics' },
  { id: 'ioc', label: 'IOC Report', icon: FileCode, description: 'Indicator of compromise listing' },
];

const formatIcons: Record<string, React.ComponentType<{ className?: string }>> = {
  pdf: FileText,
  word: FileText,
  csv: FileSpreadsheet,
  json: FileJson,
};

export default function ReportsPage() {
  const { data: reports, refetch } = useReports();
  const { data: stats } = useDashboardStats();
  const [showCreate, setShowCreate] = useState(false);
  const [newReport, setNewReport] = useState({
    title: '',
    report_type: 'incident',
    format: 'pdf',
  });
  const [generating, setGenerating] = useState(false);

  const handleGenerate = async () => {
    if (!newReport.title.trim()) {
      toast.error('Please enter a report title');
      return;
    }
    setGenerating(true);

    const summary = `This ${newReport.report_type.replace(/_/g, ' ')} report covers ${stats?.totalThreats || 0} threats, ${stats?.totalIOCs || 0} IOCs, and ${stats?.totalScams || 0} scam reports. Security score: ${stats?.securityScore || 0}/100. Threat level: ${stats?.threatLevel || 'Unknown'}.`;

    const recommendations = [
      'Implement multi-factor authentication across all external-facing services',
      'Update and test incident response procedures quarterly',
      'Deploy endpoint detection and response (EDR) on all endpoints',
      'Conduct regular phishing awareness training for all employees',
      'Review and update firewall rules to block known malicious IPs',
      'Implement network segmentation to limit lateral movement',
    ];

    const mitreMapping = {
      'T1566': { name: 'Phishing', count: stats?.threats.filter((t) => t.mitre_techniques.includes('T1566')).length || 0 },
      'T1486': { name: 'Data Encrypted for Impact', count: stats?.threats.filter((t) => t.mitre_techniques.includes('T1486')).length || 0 },
      'T1059': { name: 'Command and Scripting', count: stats?.threats.filter((t) => t.mitre_techniques.includes('T1059')).length || 0 },
    };

    const timeline = (stats?.threats || []).slice(0, 5).map((t) => ({
      time: t.detected_at,
      event: t.title,
      severity: t.severity,
    }));

    try {
      await supabase.from('reports').insert({
        title: newReport.title,
        report_type: newReport.report_type,
        format: newReport.format,
        status: 'generated',
        risk_score: stats?.securityScore || 50,
        summary,
        recommendations,
        mitre_mapping: mitreMapping,
        timeline,
        evidence: { threats: stats?.totalThreats || 0, iocs: stats?.totalIOCs || 0, scams: stats?.totalScams || 0 },
        analyst_notes: 'Report generated by SentinelX AI Analyst',
        generated_at: new Date().toISOString(),
      });
      toast.success('Report generated successfully');
      setNewReport({ title: '', report_type: 'incident', format: 'pdf' });
      setShowCreate(false);
      refetch();
    } catch {
      toast.error('Failed to generate report');
    }
    setGenerating(false);
  };

  const handleDownload = (report: { id: string; title: string; format: string; summary: string | null; recommendations: string[] }) => {
    let content = '';
    let mimeType = '';
    let extension = '';

    if (report.format === 'json') {
      content = JSON.stringify(report, null, 2);
      mimeType = 'application/json';
      extension = 'json';
    } else if (report.format === 'csv') {
      content = `Title,Type,Format,Status,Risk Score,Summary\n"${report.title}","${report.format}","${report.format}","generated","${report.summary || ''}"`;
      mimeType = 'text/csv';
      extension = 'csv';
    } else {
      content = `SENTINELX THREAT INTELLIGENCE REPORT\n${'='.repeat(50)}\n\nTitle: ${report.title}\nFormat: ${report.format.toUpperCase()}\nGenerated: ${new Date().toISOString()}\n\n${'='.repeat(50)}\n\nSUMMARY\n${'-'.repeat(20)}\n${report.summary || 'N/A'}\n\nRECOMMENDATIONS\n${'-'.repeat(20)}\n${(report.recommendations || []).map((r, i) => `${i + 1}. ${r}`).join('\n')}\n\n${'='.repeat(50)}\nGenerated by SentinelX Enterprise Threat Intelligence Platform`;
      mimeType = report.format === 'word' ? 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' : 'application/pdf';
      extension = report.format === 'word' ? 'docx' : 'txt';
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.title.replace(/\s+/g, '_')}.${extension}`;
    a.click();
    toast.success(`Report downloaded as ${extension.toUpperCase()}`);
  };

  return (
    <PageContainer>
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h2 className="text-lg font-bold">Reporting System</h2>
          <p className="text-sm text-muted-foreground">Generate professional security reports in multiple formats</p>
        </div>
        <Button onClick={() => setShowCreate(!showCreate)} className="gap-1.5">
          <Plus className="h-4 w-4" /> New Report
        </Button>
      </div>

      {showCreate && (
        <motion.div
          initial={{ opacity: 0, height: 0 }}
          animate={{ opacity: 1, height: 'auto' }}
          className="mb-6"
        >
          <Card className="border-primary/30 bg-primary/5 p-5">
            <SectionTitle title="Generate New Report" description="Select type and format" />
            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
              <div>
                <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Report Title</p>
                <Input
                  placeholder="e.g., Q3 2024 Threat Landscape Report"
                  value={newReport.title}
                  onChange={(e) => setNewReport({ ...newReport, title: e.target.value })}
                />
              </div>
              <div>
                <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Format</p>
                <div className="flex gap-2">
                  {['pdf', 'word', 'csv', 'json'].map((fmt) => {
                    const Icon = formatIcons[fmt] || FileText;
                    return (
                      <button
                        key={fmt}
                        onClick={() => setNewReport({ ...newReport, format: fmt })}
                        className={`flex flex-1 items-center justify-center gap-1.5 rounded-lg border p-2.5 text-xs font-medium uppercase transition-colors ${
                          newReport.format === fmt
                            ? 'border-primary bg-primary/10 text-primary'
                            : 'border-border text-muted-foreground hover:bg-muted'
                        }`}
                      >
                        <Icon className="h-3.5 w-3.5" />
                        {fmt}
                      </button>
                    );
                  })}
                </div>
              </div>
            </div>

            <div className="mt-4">
              <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Report Type</p>
              <div className="grid grid-cols-2 gap-2 md:grid-cols-3">
                {reportTypes.map((type) => {
                  const Icon = type.icon;
                  return (
                    <button
                      key={type.id}
                      onClick={() => setNewReport({ ...newReport, report_type: type.id })}
                      className={`flex items-start gap-2 rounded-lg border p-3 text-left transition-colors ${
                        newReport.report_type === type.id
                          ? 'border-primary bg-primary/10'
                          : 'border-border hover:bg-muted'
                      }`}
                    >
                      <Icon className={`h-4 w-4 shrink-0 ${newReport.report_type === type.id ? 'text-primary' : 'text-muted-foreground'}`} />
                      <div>
                        <p className="text-xs font-medium">{type.label}</p>
                        <p className="text-[10px] text-muted-foreground">{type.description}</p>
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>

            <div className="mt-4 flex gap-2">
              <Button onClick={handleGenerate} disabled={generating} className="gap-1.5">
                {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <FileText className="h-4 w-4" />}
                {generating ? 'Generating...' : 'Generate Report'}
              </Button>
              <Button variant="outline" onClick={() => setShowCreate(false)}>Cancel</Button>
            </div>
          </Card>
        </motion.div>
      )}

      {/* Reports list */}
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
        {(reports || []).length === 0 ? (
          <Card className="col-span-full border-border/60 p-12">
            <div className="flex flex-col items-center text-center">
              <FileText className="h-12 w-12 text-muted-foreground" />
              <p className="mt-3 text-sm font-medium">No reports yet</p>
              <p className="text-xs text-muted-foreground">Click "New Report" to generate your first report</p>
            </div>
          </Card>
        ) : (
          (reports || []).map((report, i) => {
            const FormatIcon = formatIcons[report.format] || FileText;
            return (
              <motion.div
                key={report.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.05 }}
              >
                <Card className="border-border/60 p-5 transition-colors hover:border-primary/30">
                  <div className="flex items-start justify-between">
                    <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                      <FormatIcon className="h-5 w-5 text-primary" />
                    </div>
                    <Badge variant="outline" className="text-[10px] uppercase">
                      {report.format}
                    </Badge>
                  </div>
                  <p className="mt-3 text-sm font-bold">{report.title}</p>
                  <p className="mt-1 text-xs text-muted-foreground capitalize">
                    {report.report_type.replace(/_/g, ' ')} report
                  </p>
                  {report.summary && (
                    <p className="mt-2 text-xs text-muted-foreground line-clamp-2">{report.summary}</p>
                  )}
                  <div className="mt-3 flex items-center gap-3 text-[10px] text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <Calendar className="h-3 w-3" />
                      {formatDistanceToNow(new Date(report.created_at), { addSuffix: true })}
                    </span>
                    {report.risk_score !== null && (
                      <span className="flex items-center gap-1">
                        <Shield className="h-3 w-3" />
                        Score: {report.risk_score}
                      </span>
                    )}
                    <span className="flex items-center gap-1">
                      <CheckCircle2 className="h-3 w-3 text-success" />
                      {report.status}
                    </span>
                  </div>
                  <div className="mt-3 flex gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      className="flex-1 gap-1.5"
                      onClick={() => handleDownload(report)}
                    >
                      <Download className="h-3.5 w-3.5" /> Download
                    </Button>
                    <Button variant="ghost" size="sm" className="gap-1.5">
                      <PenTool className="h-3.5 w-3.5" />
                    </Button>
                  </div>
                </Card>
              </motion.div>
            );
          })
        )}
      </div>

      {/* Report features info */}
      <Card className="mt-6 border-border/60 p-5">
        <SectionTitle title="Report Features" description="Every report includes" />
        <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
          {[
            { label: 'Company Logo', icon: Shield },
            { label: 'Interactive Charts', icon: TrendingUp },
            { label: 'Risk Score', icon: Shield },
            { label: 'Threat Summary', icon: FileText },
            { label: 'Evidence', icon: FileText },
            { label: 'Recommendations', icon: CheckCircle2 },
            { label: 'MITRE Mapping', icon: FileCode },
            { label: 'Timeline', icon: Calendar },
            { label: 'Analyst Notes', icon: PenTool },
            { label: 'Digital Signature', icon: Shield },
          ].map((feature) => {
            const Icon = feature.icon;
            return (
              <div key={feature.label} className="flex items-center gap-2 rounded-lg border border-border/50 p-3">
                <Icon className="h-4 w-4 text-primary" />
                <span className="text-xs font-medium">{feature.label}</span>
              </div>
            );
          })}
        </div>
      </Card>
    </PageContainer>
  );
}
